# -*- coding: utf-8 -*-
"""
Gera uma lista de 1000 temas variados (sem repetição), organizados por categoria,
e grava na planilha data/temas.xlsx no formato esperado pelo bot.
"""

temas_por_categoria = {
    "Ciência": [
        "Por que o céu é azul", "Como funciona a gravidade", "O que é o efeito borboleta",
        "Como surgem os arco-íris", "O que são buracos negros", "Como funciona um terremoto",
        "Por que os vulcões entram em erupção", "O que é a velocidade da luz",
        "Como funciona a fotossíntese", "O que é DNA e para que serve",
        "Como o som viaja no ar", "Por que a água vira gelo", "O que é energia cinética",
        "Como funcionam os imãs", "O que é a tabela periódica", "Como surgem os fósseis",
        "O que é radioatividade", "Como funciona o efeito estufa", "O que são ondas eletromagnéticas",
        "Como a Terra se formou", "Por que existem estações do ano", "O que é matéria escura",
        "Como funciona a eletricidade estática", "O que são células-tronco",
        "Como o cérebro processa imagens", "O que é a teoria da relatividade",
        "Como funciona um laser", "Por que o gelo flutua na água", "O que é entropia",
        "Como se formam as nuvens", "O que é a tensão superficial", "Como funciona o pH",
        "O que são enzimas", "Como ocorre a mutação genética", "O que é biomimética",
        "Como funciona a clonagem", "O que é nanotecnologia", "Como se mede a temperatura",
        "O que são ondas sísmicas", "Como funciona a osmose", "O que é o número de Avogadro",
        "Por que metais conduzem eletricidade", "Como funciona a fusão nuclear",
        "O que é a fissão nuclear", "Como surgem os cristais", "O que é o efeito Doppler",
        "Como funciona a refração da luz", "O que são isótopos", "Como ocorre a evaporação",
        "O que é o princípio de Arquimedes", "Como funciona a inércia",
    ],
    "Saúde": [
        "Como funciona a vacina", "Benefícios de beber água", "Como funciona o sistema imunológico",
        "Por que dormimos", "O que causa a febre", "Como funciona a digestão",
        "Benefícios da atividade física", "O que é colesterol", "Como funciona a insulina",
        "Por que sentimos dor", "O que é pressão alta", "Como funciona a memória",
        "Benefícios de uma boa postura", "O que são probióticos", "Como funciona a respiração",
        "Por que bocejamos", "O que é o sistema linfático", "Como funciona a coagulação do sangue",
        "Benefícios da meditação", "O que é metabolismo", "Como funciona a visão",
        "Por que envelhecemos", "O que é o microbioma intestinal", "Como funciona a audição",
        "Benefícios do sono profundo", "O que são anticorpos", "Como funciona a cicatrização",
        "Por que temos alergias", "O que é o efeito placebo", "Como funciona a tireoide",
        "Benefícios de uma dieta equilibrada", "O que é hidratação celular",
        "Como funcionam as vitaminas", "Por que sentimos fome", "O que é o ciclo circadiano",
        "Como funciona o sistema nervoso", "Benefícios de alongar o corpo",
        "O que são radicais livres", "Como funciona a vacinação em massa",
        "Por que o estresse afeta a saúde", "O que é saúde mental", "Como funciona a ansiedade",
        "Benefícios de reduzir o açúcar", "O que é intolerância alimentar",
        "Como funciona o sistema cardiovascular", "Por que fazemos check-ups regulares",
        "O que é hipertensão", "Como funciona a cicatrização óssea", "Benefícios da hidroterapia",
        "O que é a saúde bucal e por que importa",
    ],
    "Tecnologia": [
        "Como funciona a internet", "O que é inteligência artificial", "Como funciona um smartphone",
        "O que é blockchain", "Como funciona o Wi-Fi", "O que é realidade virtual",
        "Como funciona um computador quântico", "O que é machine learning",
        "Como funciona o GPS", "O que é 5G", "Como funcionam os códigos de barras",
        "O que é criptografia", "Como funciona um chip de memória", "O que é a nuvem (cloud)",
        "Como funcionam os carros elétricos", "O que é realidade aumentada",
        "Como funciona o reconhecimento facial", "O que são chatbots",
        "Como funciona um drone", "O que é Internet das Coisas (IoT)",
        "Como funcionam os painéis solares", "O que é um algoritmo",
        "Como funciona a impressão 3D", "O que são robôs autônomos",
        "Como funciona o Bluetooth", "O que é biometria", "Como surgiu a internet",
        "O que é um data center", "Como funciona o streaming de vídeo",
        "O que é cibersegurança", "Como funciona um carro autônomo",
        "O que são redes neurais artificiais", "Como funciona a tela touch screen",
        "O que é um sistema operacional", "Como funcionam os satélites de comunicação",
        "O que é deep learning", "Como funciona o reconhecimento de voz",
        "O que é a Web3", "Como funcionam as baterias de lítio",
        "O que é computação em nuvem", "Como funciona um QR Code",
    ],
    "Curiosidades": [
        "Como surgiu o café", "A história do chocolate", "Por que o mar é salgado",
        "Como surgiu a pizza", "A origem dos emojis", "Por que usamos 24 horas no dia",
        "Como surgiu o alfabeto", "A história do papel", "Por que o ouro é valioso",
        "Como surgiu a moeda", "A origem dos números", "Por que dizemos 'OK'",
        "Como surgiu a roda", "A história do sabão", "Por que existem fusos horários",
        "Como surgiu o calendário", "A origem do xadrez", "Por que usamos talheres",
        "Como surgiu a escrita", "A história dos óculos", "Por que existe o ano bissexto",
        "Como surgiu o futebol", "A origem da pizza margherita", "Por que trocamos de roupa íntima",
        "Como surgiu o cinema", "A história da fotografia", "Por que usamos guarda-chuva",
        "Como surgiu o relógio", "A origem do dinheiro de papel", "Por que existem fusos diferentes",
        "Como surgiu a bandeira", "A história do correio", "Por que comemos bolo de aniversário",
        "Como surgiu o cartão postal", "A origem do hino nacional", "Por que usamos anéis de casamento",
        "Como surgiu a moda jeans", "A história dos sapatos", "Por que existem fogos de artifício",
        "Como surgiu o chá", "A origem da pipoca", "Por que decoramos árvores de Natal",
        "Como surgiu o sorvete", "A história das pirâmides", "Por que usamos garfo e faca",
        "Como surgiu o papel moeda", "A origem do circo", "Por que existem feriados",
        "Como surgiu a escrita cuneiforme", "A história do correio postal",
    ],
    "Meio Ambiente": [
        "Como funciona a reciclagem de plástico", "Diferença entre clima e tempo",
        "Como economizar energia em casa", "O que é aquecimento global",
        "Como funciona a compostagem", "O que é pegada de carbono",
        "Como funciona a energia eólica", "O que é desmatamento",
        "Como funciona a captação de água da chuva", "O que é biodiversidade",
        "Como funciona a poluição do ar", "O que são energias renováveis",
        "Como funciona o ciclo da água", "O que é economia circular",
        "Como funciona a preservação de espécies", "O que é poluição sonora",
        "Como funciona a agricultura sustentável", "O que é o buraco na camada de ozônio",
        "Como funciona a reciclagem de vidro", "O que são microplásticos",
        "Como funciona a conservação de oceanos", "O que é consumo consciente",
        "Como funciona a reciclagem de papel", "O que é extinção de espécies",
        "Como funciona o efeito ilha de calor", "O que são créditos de carbono",
        "Como funciona a despoluição de rios", "O que é permacultura",
        "Como funciona a reciclagem de eletrônicos", "O que é biocombustível",
        "Como funciona o derretimento das geleiras", "O que é manejo florestal",
        "Como funciona a proteção de mananciais", "O que é energia geotérmica",
        "Como funciona a reciclagem de óleo de cozinha", "O que é greenwashing",
        "Como funciona o saneamento básico", "O que é agrofloresta",
    ],
    "Astronomia": [
        "Como funciona um eclipse", "O que são constelações", "Como surgiu a Lua",
        "O que é um buraco negro", "Como funcionam os telescópios", "O que é a Via Láctea",
        "Como surgem as estrelas", "O que é um exoplaneta", "Como funciona a gravidade no espaço",
        "O que são meteoros e meteoritos", "Como funciona a Estação Espacial Internacional",
        "O que é o sistema solar", "Como surgiu o universo", "O que são anéis de Saturno",
        "Como funciona um foguete", "O que é uma supernova", "Como os astronautas vivem no espaço",
        "O que é a velocidade de escape", "Como funciona a fase da Lua",
        "O que são marés e por que existem", "Como funciona um satélite artificial",
        "O que é a Estrela do Norte", "Como funciona um eclipse lunar",
        "O que é matéria interestelar", "Como funcionam as sondas espaciais",
        "O que é Marte e por que é estudado", "Como funciona a radiação cósmica",
        "O que são galáxias espirais", "Como funciona um ano-luz",
        "O que é o Big Bang", "Como funciona a órbita dos planetas",
        "O que é a Nebulosa", "Como funciona um asteroide", "O que é Plutão hoje",
        "Como os planetas foram descobertos", "O que é zona habitável",
    ],
    "Animais": [
        "Como as aves migram tão longe", "Por que os camaleões mudam de cor",
        "Como os morcegos veem no escuro", "Por que os pinguins não voam",
        "Como as abelhas produzem mel", "Por que os gatos ronronam",
        "Como os elefantes se comunicam", "Por que os cachorros abanam o rabo",
        "Como os polvos mudam de forma", "Por que as zebras têm listras",
        "Como os tubarões detectam presas", "Por que as girafas têm pescoço longo",
        "Como as formigas se organizam", "Por que os ursos hibernam",
        "Como os peixes respiram embaixo da água", "Por que as borboletas têm cores vibrantes",
        "Como os cavalos dormem em pé", "Por que os corvos são tão inteligentes",
        "Como as tartarugas vivem tanto tempo", "Por que os leões vivem em grupo",
        "Como os camelos sobrevivem no deserto", "Por que os flamingos ficam em uma perna só",
        "Como as cobras enxergam sem pálpebras", "Por que os coalas dormem tanto",
        "Como os delfins se comunicam", "Por que os pavões abrem a plumagem",
        "Como as aranhas tecem teias", "Por que os ursos polares têm pelo branco",
        "Como os esquilos guardam comida", "Por que os cangurus saltam tão alto",
        "Como as lulas se camuflam", "Por que as raposas têm cauda longa",
    ],
    "Sustentabilidade": [
        "Como funciona o consumo consciente", "O que é moda sustentável",
        "Como reduzir o desperdício de alimentos", "O que é mobilidade urbana sustentável",
        "Como funciona a energia solar residencial", "O que é construção sustentável",
        "Como reduzir o uso de plástico no dia a dia", "O que é compostagem doméstica",
        "Como funciona o transporte público sustentável", "O que é horta urbana",
        "Como economizar água em casa", "O que é upcycling",
        "Como funciona a coleta seletiva", "O que é pegada hídrica",
        "Como reduzir o consumo de energia elétrica", "O que é economia compartilhada",
        "Como funciona o turismo sustentável", "O que são produtos biodegradáveis",
        "Como reduzir o lixo eletrônico", "O que é certificação ambiental",
    ],
    "Psicologia": [
        "Como funciona a procrastinação", "O que é inteligência emocional",
        "Como funciona a memória de curto prazo", "O que é viés de confirmação",
        "Como funciona o medo", "O que é autoestima", "Como funciona a motivação",
        "O que é resiliência", "Como funciona o estresse", "O que é empatia",
        "Como funciona a tomada de decisão", "O que é mentalidade de crescimento",
        "Como funciona o esquecimento", "O que é gatilho emocional",
        "Como funciona a procrastinação digital", "O que é autossabotagem",
        "Como funciona o efeito halo", "O que é dissonância cognitiva",
        "Como funciona a comparação social", "O que é síndrome do impostor",
        "Como funciona a gratidão", "O que é inteligência social",
        "Como funciona o hábito", "O que é foco e atenção plena",
        "Como funciona a primeira impressão", "O que é assertividade",
    ],
    "História": [
        "Como surgiu a Roma Antiga", "A história das Olimpíadas", "Como surgiu a escrita egípcia",
        "A história da Grande Muralha da China", "Como surgiu o Império Romano",
        "A história das Cruzadas", "Como surgiu a Revolução Industrial",
        "A história da Idade Média", "Como surgiu a democracia ateniense",
        "A história dos Vikings", "Como surgiu o Renascimento", "A história da Revolução Francesa",
        "Como surgiu a fotografia em preto e branco", "A história das Grandes Navegações",
        "Como surgiu a imprensa", "A história do Egito Antigo", "Como surgiu a Guerra Fria",
        "A história da Rota da Seda", "Como surgiu a moeda romana", "A história dos Maias",
        "Como surgiu a escrita cuneiforme", "A história do Coliseu",
        "Como surgiu a Declaração de Independência dos EUA", "A história das pirâmides do Egito",
        "Como surgiu o Império Bizantino", "A história da Peste Negra",
        "Como surgiu a Revolução Russa", "A história da Muralha de Berlim",
        "Como surgiu o Império Inca", "A história da chegada à Lua",
    ],
    "Alimentação": [
        "Como funciona a fermentação", "Benefícios das frutas vermelhas",
        "Como surgiu o pão", "Benefícios dos grãos integrais", "Como funciona a pasteurização",
        "Benefícios das oleaginosas", "Como surgiu o queijo", "Benefícios do azeite de oliva",
        "Como funciona a conservação de alimentos", "Benefícios dos vegetais verde-escuros",
        "Como surgiu o vinho", "Benefícios das leguminosas", "Como funciona a maturação de frutas",
        "Benefícios do consumo de peixe", "Como surgiu o iogurte",
        "Benefícios de reduzir o sal", "Como funciona a refrigeração de alimentos",
        "Benefícios das fibras alimentares", "Como surgiu o açúcar refinado",
        "Benefícios de uma alimentação colorida", "Como funciona o congelamento de alimentos",
        "Benefícios dos chás naturais", "Como surgiu o mel", "Benefícios de comer devagar",
        "Como funciona a digestão da lactose",
    ],
    "Finanças": [
        "Como funciona a inflação", "O que é taxa de juros", "Como funciona o orçamento pessoal",
        "O que é investimento de renda fixa", "Como funciona o cartão de crédito",
        "O que é reserva de emergência", "Como funciona a bolsa de valores",
        "O que é score de crédito", "Como funciona o financiamento", "O que é juros compostos",
        "Como funciona a poupança", "O que é diversificação de investimentos",
        "Como funciona o consórcio", "O que é inadimplência", "Como funciona o Pix",
        "O que é educação financeira", "Como funciona o planejamento de aposentadoria",
        "O que é fundo de investimento", "Como funciona o câmbio de moedas",
        "O que é independência financeira",
    ],
    "Geografia": [
        "Como se formam as montanhas", "O que são placas tectônicas",
        "Como se formam os desertos", "O que são correntes marítimas",
        "Como se formam os rios", "O que é o equador", "Como se formam as ilhas",
        "O que são biomas", "Como se formam os cânions", "O que é relevo cárstico",
        "Como se formam as cachoeiras", "O que é clima tropical",
        "Como se formam os vulcões submarinos", "O que são savanas",
        "Como se formam os lagos", "O que é tundra", "Como se formam os recifes de coral",
        "O que é floresta tropical", "Como se formam os deltas de rio",
        "O que é zona de convergência climática",
    ],
    "Esportes": [
        "Como funciona o sistema de pontuação no tênis", "A origem das Olimpíadas modernas",
        "Como funciona o impedimento no futebol", "A história da Copa do Mundo",
        "Como funciona o judô", "A origem do basquete", "Como funciona o atletismo de revezamento",
        "A história das maratonas", "Como funciona o sistema de cintos no jiu-jitsu",
        "A origem do vôlei", "Como funciona o doping em esportes", "A história das paralimpíadas",
        "Como funciona o handicap no golfe", "A origem do rúgbi",
        "Como funciona o nado sincronizado", "A história do ciclismo de estrada",
    ],
    "Música e Arte": [
        "Como funciona a leitura de partituras", "A origem do jazz",
        "Como funciona a afinação de instrumentos", "A história da música clássica",
        "Como funciona o ritmo musical", "A origem do hip hop",
        "Como funciona a perspectiva na pintura", "A história do impressionismo",
        "Como funciona a técnica do grafite", "A origem do samba",
        "Como funciona a escultura em mármore", "A história da Mona Lisa",
        "Como funciona um coral", "A origem do rock and roll",
        "Como funciona a fotografia analógica", "A história da Bossa Nova",
        "Como funciona a técnica do mosaico", "A origem do reggae",
        "Como funciona a harmonia musical", "A história da Capela Sistina",
        "Como funciona o teatro de sombras", "A origem do balé clássico",
        "Como funciona a técnica de aquarela", "A história do MPB",
        "Como funciona a ópera", "A origem do funk brasileiro",
        "Como funciona a escultura em bronze", "A história da Guernica de Picasso",
        "Como funciona a improvisação no jazz", "A origem do blues",
        "Como funciona a cerâmica artesanal", "A história do graffiti urbano",
    ],
    "Corpo Humano": [
        "Como funciona o coração", "O que são os pulmões e como funcionam",
        "Como funciona o fígado", "O que são os rins e sua função",
        "Como funciona o cérebro humano", "O que é a pele e suas camadas",
        "Como funcionam os músculos", "O que são os ossos e o esqueleto",
        "Como funciona o pâncreas", "O que é o estômago e a digestão",
        "Como funcionam as articulações", "O que são os neurônios",
        "Como funciona o sistema reprodutor", "O que é a medula espinhal",
        "Como funciona o intestino", "O que são as glândulas endócrinas",
        "Como funciona o olfato", "O que é o paladar e como funciona",
        "Como funciona o tato", "O que são os reflexos do corpo",
        "Como funciona a voz humana", "O que é o sistema vestibular (equilíbrio)",
        "Como funcionam os dentes", "O que é a unha e como cresce",
        "Como funciona o cabelo e seu crescimento", "O que é o suor e sua função",
    ],
    "Espaço e Universo": [
        "O que é a teoria do multiverso", "Como os cientistas buscam vida extraterrestre",
        "O que é a sonda Voyager", "Como funciona um telescópio espacial",
        "O que é a radiação cósmica de fundo", "Como os astronautas treinam",
        "O que é gravidade zero", "Como funciona um traje espacial",
        "O que é a corrida espacial", "Como funciona o pouso em outros planetas",
        "O que é energia escura", "Como os planetas são nomeados",
        "O que é uma estrela de nêutrons", "Como funciona a comunicação no espaço",
        "O que é o cinturão de Kuiper", "Como os cometas se formam",
        "O que é a missão a Marte", "Como funciona a colonização espacial (teoria)",
        "O que são as luas de Júpiter", "Como funciona um eclipse solar total",
    ],
    "Idiomas e Comunicação": [
        "Como surgiram os idiomas", "Por que existem tantas línguas no mundo",
        "Como funciona a tradução automática", "O que é a língua de sinais",
        "Como surgiu o português", "Por que palavras mudam de significado com o tempo",
        "Como funciona o braile", "O que são línguas em extinção",
        "Como surgiu o latim e sua influência", "Por que existem gírias regionais",
        "Como funciona o alfabeto fonético", "O que é bilinguismo e seus benefícios",
        "Como surgiram os emojis como linguagem", "Por que existem acentos regionais",
        "Como funciona a leitura labial", "O que é a etimologia das palavras",
    ],
    "Direito e Sociedade": [
        "Como funciona o sistema eleitoral", "O que são os poderes do Estado",
        "Como funciona uma constituição", "O que é cidadania",
        "Como funciona o júri popular", "O que são direitos humanos",
        "Como funciona a separação de poderes", "O que é democracia direta x representativa",
        "Como funciona o processo legislativo", "O que é Estado de Direito",
        "Como funciona o direito do consumidor", "O que é a Declaração Universal dos Direitos Humanos",
        "Como funciona o voto obrigatório", "O que são políticas públicas",
    ],
    "Educação": [
        "Como funciona a curva do esquecimento", "O que é aprendizagem ativa",
        "Como funciona a repetição espaçada", "O que é educação à distância",
        "Como funciona a alfabetização", "O que é pensamento crítico",
        "Como funciona a gamificação no ensino", "O que é neuroeducação",
        "Como funciona o ensino híbrido", "O que é currículo escolar",
        "Como funciona a avaliação formativa", "O que é educação inclusiva",
    ],
    "Transportes": [
        "Como funciona um avião", "Como funciona um trem-bala",
        "Como funciona um navio cargueiro", "Como funciona o motor a combustão",
        "Como funciona um elevador", "Como funciona o metrô",
        "Como funciona uma ponte suspensa", "Como funciona um submarino",
        "Como funciona o radar de trânsito", "Como funciona um helicóptero",
        "Como funciona a aerodinâmica dos carros", "Como funciona um pneu",
        "Como funciona o sistema de freios ABS", "Como funciona um foguete reutilizável",
        "Como funciona a navegação marítima", "Como funciona um teleférico",
    ],
    "Curiosidades Científicas": [
        "Por que bocejar é contagioso", "Por que sentimos cócegas",
        "Por que choramos quando cortamos cebola", "Por que sentimos sono depois de comer",
        "Por que os dedos enrugam na água", "Por que sentimos tontura ao girar",
        "Por que o nariz coça quando vamos chorar", "Por que sentimos frio com febre",
        "Por que o estômago resmunga", "Por que sentimos dor de cabeça",
        "Por que suamos quando estamos nervosos", "Por que sentimos calafrios",
        "Por que a voz muda na puberdade", "Por que sentimos saudade",
        "Por que rimos quando alguém cai", "Por que sentimos medo do escuro",
        "Por que o coração bate mais rápido com medo", "Por que sentimos déjà vu",
        "Por que sentimos preguiça pela manhã", "Por que bocejamos ao ver outros bocejando",
    ],
    "Inovação e Negócios": [
        "Como funciona uma startup", "O que é modelo de negócio escalável",
        "Como funciona o crowdfunding", "O que é economia da atenção",
        "Como funciona o marketing digital", "O que é branding",
        "Como funciona uma franquia", "O que é inovação disruptiva",
        "Como funciona o e-commerce", "O que é experiência do cliente",
        "Como funciona o networking profissional", "O que é propriedade intelectual",
        "Como funciona um plano de negócios", "O que é cultura organizacional",
    ],
}


# Lista de objetos/fenômenos do dia a dia para gerar temas extras do tipo
# "Como funciona X" / "A história de X", cobrindo o que falta para chegar a 1000
# sem repetir os temas já escritos manualmente acima.
objetos_cotidianos = [
    "o micro-ondas", "a geladeira", "o ar-condicionado", "a máquina de lavar roupa",
    "o forno elétrico", "a torradeira", "o aspirador de pó", "o liquidificador",
    "a cafeteira elétrica", "o ferro de passar roupa", "a lâmpada incandescente",
    "a lâmpada LED", "o chuveiro elétrico", "a fechadura eletrônica", "o termômetro digital",
    "a balança digital", "o controle remoto", "a pilha alcalina", "a bateria recarregável",
    "o carregador de celular", "o fone de ouvido sem fio", "a caixa de som bluetooth",
    "o relógio de pulso mecânico", "a fivela de cinto", "o zíper", "o velcro",
    "a caneta esferográfica", "o lápis de grafite", "a borracha escolar", "o clipe de papel",
    "o post-it", "a fita adesiva", "o papel alumínio", "o plástico filme",
    "a embalagem tetra pak", "a lata de alumínio", "o vidro reciclável", "o isopor",
    "a vela de cera", "o fósforo", "o isqueiro", "a panela de pressão",
    "a frigideira antiaderente", "o filtro de café", "a peneira de cozinha", "o descascador de legumes",
    "a tábua de cortar", "o ralador de queijo", "o abridor de garrafas", "o saca-rolhas",
    "a esponja de lavar louça", "o detergente", "o sabão em pó", "o amaciante de roupas",
    "a vassoura", "o rodo", "o balde", "a mangueira de jardim",
    "o termostato", "o sensor de movimento", "o alarme contra incêndio", "o extintor de incêndio",
    "a fechadura biométrica", "a campainha eletrônica", "o interfone", "a câmera de segurança",
    "o pneu de bicicleta", "o freio a disco", "a corrente de bicicleta", "o capacete de proteção",
    "o cinto de segurança", "o airbag do carro", "o limpador de para-brisa", "o farol de LED",
    "a bússola", "o barômetro", "o sextante", "o relógio de sol",
    "o ábaco", "a régua de cálculo", "a calculadora eletrônica", "o teclado de computador",
    "o mouse de computador", "a impressora", "o scanner", "o roteador de internet",
    "o modem", "o cabo de fibra óptica", "o pendrive", "o cartão de memória",
    "o código Morse", "o telégrafo", "o telefone fixo", "o fax",
    "o rádio AM/FM", "a antena parabólica", "a televisão de tubo", "a tela de plasma",
    "o projetor de cinema", "a câmera fotográfica analógica", "o filme fotográfico", "o flash de câmera",
    "o binóculo", "a luneta", "o microscópio", "o estetoscópio",
    "o termômetro de mercúrio", "o aparelho de pressão arterial", "o oxímetro", "o desfibrilador",
    "a seringa", "o curativo adesivo", "a gaze", "o álcool em gel",
    "o sabonete antibacteriano", "o protetor solar", "o repelente de insetos", "a pasta de dente",
    "o fio dental", "a escova de dentes elétrica", "o aparelho ortodôntico", "a lente de contato",
    "os óculos de grau", "o aparelho auditivo", "a cadeira de rodas", "a muleta",
    "o andador ortopédico", "a prótese mecânica", "o marca-passo", "a mochila escolar",
    "o estojo escolar", "o quadro branco", "o projetor multimídia", "o data show",
    "a mesa digitalizadora", "o leitor de QR Code", "a etiqueta RFID", "o cartão magnético",
    "o chip do cartão de crédito", "a maquininha de cartão", "o caixa eletrônico", "o cofre digital",
    "o detector de metais", "o scanner corporal de aeroporto", "o raio-x", "a ressonância magnética",
    "a tomografia computadorizada", "o ultrassom médico", "o eletrocardiograma", "a vacina em spray nasal",
]


def gerar_temas_extras_combinados():
    """Gera temas do tipo 'Como funciona X' a partir da lista de objetos cotidianos."""
    extras = []
    for objeto in objetos_cotidianos:
        extras.append((f"Como funciona {objeto}", "Tecnologia e Cotidiano"))
    return extras


pares_diferencas = [
    ("vírus", "bactéria"), ("alergia", "intolerância"), ("doce", "salgado"),
    ("réptil", "anfíbio"), ("planeta", "estrela"), ("meteoro", "meteorito"),
    ("furacão", "tornado"), ("rio", "riacho"), ("lago", "lagoa"),
    ("ouro", "prata"), ("diamante", "grafite"), ("ácido", "base"),
    ("som", "ruído"), ("calor", "temperatura"), ("massa", "peso"),
    ("velocidade", "aceleração"), ("clima tropical", "clima equatorial"),
    ("herbívoro", "carnívoro"), ("vertebrado", "invertebrado"),
    ("economia", "finanças"), ("poupança", "investimento"),
    ("ação", "fundo de investimento"), ("franquia", "negócio próprio"),
    ("liderança", "gestão"), ("eficiência", "eficácia"),
    ("ansiedade", "estresse"), ("introvertido", "tímido"),
    ("empatia", "compaixão"), ("memória de curto prazo", "memória de longo prazo"),
    ("hardware", "software"), ("internet", "intranet"),
    ("vírus de computador", "malware"), ("Wi-Fi", "dados móveis"),
    ("streaming", "download"), ("nuvem pública", "nuvem privada"),
    ("democracia", "república"), ("lei", "decreto"),
    ("monarquia", "república"), ("globalização", "protecionismo"),
    ("clima", "tempo atmosférico"), ("reciclar", "reutilizar"),
    ("biodegradável", "compostável"), ("vegano", "vegetariano"),
    ("orgânico", "natural"), ("caloria", "nutriente"),
    ("proteína", "carboidrato"), ("gordura saturada", "gordura insaturada"),
    ("vitamina hidrossolúvel", "vitamina liposolúvel"), ("fungo", "planta"),
    ("DNA", "RNA"), ("célula animal", "célula vegetal"),
    ("evolução", "adaptação"), ("ecossistema", "habitat"),
]


def gerar_temas_diferencas():
    extras = []
    for a, b in pares_diferencas:
        extras.append((f"Qual a diferença entre {a} e {b}", "Comparações e Diferenças"))
    return extras


curiosidades_numericas = [
    "Quantos litros de sangue o corpo humano tem", "Quantos ossos tem o esqueleto humano",
    "Quantas vezes o coração bate por dia", "Quanto tempo leva para a luz do Sol chegar à Terra",
    "Quantos músculos usamos para sorrir", "Quanto tempo dura a digestão completa",
    "Quantos litros de ar respiramos por dia", "Quantas células o corpo humano tem",
    "Quanto tempo um avião leva para cruzar o Atlântico", "Quantos planetas existem no sistema solar",
    "Quanto tempo a Terra leva para dar uma volta no Sol", "Quantas espécies de animais existem no mundo",
    "Quanto tempo leva para uma árvore crescer", "Quantos litros de água um ser humano precisa por dia",
    "Quanto tempo dura a memória de curto prazo", "Quantas horas de sono um adulto precisa",
    "Quanto tempo leva para formar um diamante", "Quantos quilômetros tem a Grande Muralha da China",
    "Quanto tempo um cometa leva para orbitar o Sol", "Quantas linguagens de programação existem",
]


profissoes_e_processos = [
    "Como funciona o trabalho de um piloto de avião", "Como funciona o trabalho de um astronauta",
    "Como funciona o trabalho de um cirurgião", "Como funciona o trabalho de um juiz",
    "Como funciona o trabalho de um bombeiro", "Como funciona o trabalho de um arqueólogo",
    "Como funciona o trabalho de um meteorologista", "Como funciona o trabalho de um tradutor",
    "Como funciona o trabalho de um arquiteto", "Como funciona o trabalho de um engenheiro civil",
    "Como funciona o trabalho de um programador", "Como funciona o trabalho de um veterinário",
    "Como funciona o trabalho de um nutricionista", "Como funciona o trabalho de um psicólogo",
    "Como funciona o trabalho de um fisioterapeuta", "Como funciona o trabalho de um dentista",
    "Como funciona o trabalho de um farmacêutico", "Como funciona o trabalho de um biólogo marinho",
    "Como funciona o trabalho de um astrônomo", "Como funciona o trabalho de um geólogo",
    "Como funciona o trabalho de um piloto de Fórmula 1", "Como funciona o trabalho de um detetive",
    "Como funciona o trabalho de um diplomata", "Como funciona o trabalho de um jornalista",
    "Como funciona o trabalho de um economista", "Como funciona o trabalho de um cientista de dados",
    "Como funciona o processo de fabricação de um carro", "Como funciona o processo de fabricação do papel",
    "Como funciona o processo de fabricação do vidro", "Como funciona o processo de fabricação de roupas",
    "Como funciona o processo de fabricação do chocolate", "Como funciona o processo de fabricação da cerveja",
    "Como funciona o processo de fabricação do queijo", "Como funciona o processo de fabricação do plástico",
    "Como funciona o processo de fabricação de remédios", "Como funciona o processo de fabricação de aviões",
    "Como funciona o processo eleitoral no Brasil", "Como funciona o processo de aprovação de uma lei",
    "Como funciona o processo de vacinação infantil", "Como funciona o processo de reciclagem de latas",
    "Como funciona o processo de purificação da água", "Como funciona o processo de tratamento de esgoto",
    "Como funciona o processo de produção de energia elétrica", "Como funciona o processo de extração de petróleo",
    "Como funciona o processo de mineração", "Como funciona o processo de produção de aço",
    "Como funciona o processo de impressão de jornais", "Como funciona o processo de dublagem de filmes",
    "Como funciona o processo de produção de um filme", "Como funciona o processo de gravação de um álbum musical",
    "Como funciona o processo de revisão por pares na ciência", "Como funciona o processo de patenteamento de invenções",
    "Como funciona o processo de adoção", "Como funciona o processo de naturalização de um imigrante",
    "Como funciona o processo de aposentadoria", "Como funciona o processo de declaração do imposto de renda",
    "Como funciona o processo de abertura de uma empresa", "Como funciona o processo de falência de uma empresa",
    "Como funciona o processo de fusão entre empresas", "Como funciona o processo de IPO (abertura de capital)",
    "Como funciona o processo de auditoria financeira", "Como funciona o processo de certificação de qualidade",
    "Como funciona o processo de produção de vinho", "Como funciona o processo de torrefação do café",
    "Como funciona o processo de cura da carne", "Como funciona o processo de pasteurização do leite",
    "Como funciona o processo de fermentação do pão", "Como funciona o processo de maturação do queijo",
    "Como funciona o processo de destilação", "Como funciona o processo de filtragem de óleo",
    "Como funciona o processo de soldagem", "Como funciona o processo de usinagem de metais",
    "Como funciona o processo de impressão 3D de uma peça", "Como funciona o processo de montagem de um celular",
    "Como funciona o processo de testes de um novo remédio", "Como funciona o processo de ensaio clínico",
    "Como funciona o processo de transplante de órgãos", "Como funciona o processo de doação de sangue",
    "Como funciona o processo de quarentena sanitária", "Como funciona o processo de triagem hospitalar",
    "Como funciona o processo de perícia criminal", "Como funciona o processo de identificação por digital",
    "Como funciona o processo de extradição internacional", "Como funciona o processo de asilo político",
    "Como funciona o processo de mediação de conflitos", "Como funciona o processo de arbitragem comercial",
    "Como funciona o processo de licitação pública", "Como funciona o processo de concurso público",
    "Como funciona o processo seletivo de uma vaga de emprego", "Como funciona o processo de recrutamento militar",
    "Como funciona o processo de formação de um furacão", "Como funciona o processo de formação da chuva",
    "Como funciona o processo de formação do orvalho", "Como funciona o processo de formação do granizo",
    "Como funciona o processo de formação da neve", "Como funciona o processo de formação de um deserto",
    "Como funciona o processo de erosão do solo", "Como funciona o processo de sedimentação dos rios",
    "Como funciona o processo de fotossíntese nas algas", "Como funciona o processo de germinação de uma semente",
    "Como funciona o processo de polinização das flores", "Como funciona o processo de metamorfose das borboletas",
    "Como funciona o processo de hibernação dos ursos", "Como funciona o processo de migração das baleias",
    "Como funciona o processo de camuflagem dos animais", "Como funciona o processo de domesticação dos cães",
    "Como funciona o processo de seleção natural", "Como funciona o processo de especiação de novas espécies",
    "Como funciona o processo de envelhecimento celular", "Como funciona o processo de cicatrização de feridas",
    "Como funciona o processo de formação de cálculos renais", "Como funciona o processo de absorção de nutrientes",
    "Como funciona o processo de produção de hormônios", "Como funciona o processo de regeneração celular",
    "Como funciona o processo de formação da memória", "Como funciona o processo de aprendizagem no cérebro",
    "Como funciona o processo de sonhar durante o sono", "Como funciona o processo de despertar do corpo",
    "Como funciona o processo criativo de um artista", "Como funciona o processo de composição musical",
    "Como funciona o processo de roteirização de um filme", "Como funciona o processo de animação de desenhos",
    "Como funciona o processo de dublagem em outro idioma", "Como funciona o processo de legendagem de vídeos",
    "Como funciona o processo de transmissão ao vivo na internet", "Como funciona o processo de moderação de redes sociais",
    "Como funciona o processo de indexação do Google", "Como funciona o processo de recomendação de algoritmos",
    "Como funciona o processo de criptografia de dados bancários", "Como funciona o processo de autenticação em dois fatores",
    "Como funciona o processo de backup de dados na nuvem", "Como funciona o processo de atualização de software",
    "Como funciona o processo de lançamento de um foguete", "Como funciona o processo de reentrada na atmosfera",
    "Como funciona o processo de acoplamento espacial", "Como funciona o processo de pouso lunar",
    "Como funciona o processo de captação de energia solar", "Como funciona o processo de armazenamento de energia em baterias",
    "Como funciona o processo de geração de energia eólica", "Como funciona o processo de geração de energia hidrelétrica",
    "Como funciona o processo de dessalinização da água do mar", "Como funciona o processo de irrigação agrícola",
    "Como funciona o processo de rotação de culturas", "Como funciona o processo de adubação do solo",
    "Como funciona o processo de colheita mecanizada", "Como funciona o processo de armazenamento de grãos",
    "Como funciona o processo de pasteurização de sucos", "Como funciona o processo de envase de bebidas",
    "Como funciona o processo de rotulagem de produtos", "Como funciona o processo de logística de entrega",
    "Como funciona o processo de rastreamento de encomendas", "Como funciona o processo de armazenagem em centros de distribuição",
    "Como funciona o processo de fabricação de pneus",
]


def gerar_lista_completa(total=1000):
    temas = []
    for categoria, lista in temas_por_categoria.items():
        for tema in lista:
            temas.append((tema, categoria))

    temas.extend(gerar_temas_extras_combinados())
    temas.extend(gerar_temas_diferencas())
    temas.extend((t, "Curiosidades Numéricas") for t in curiosidades_numericas)
    temas.extend((t, "Profissões e Processos") for t in profissoes_e_processos)

    # remove eventuais duplicatas mantendo ordem
    vistos = set()
    unicos = []
    for tema, categoria in temas:
        if tema not in vistos:
            vistos.add(tema)
            unicos.append((tema, categoria))

    if len(unicos) < total:
        raise ValueError(
            f"Lista base tem {len(unicos)} temas únicos, menor que o total solicitado ({total})."
        )

    return unicos[:total]


if __name__ == "__main__":
    lista = gerar_lista_completa(1000)
    print(f"Total de temas únicos gerados: {len(lista)}")
